#!/usr/bin/env python
"""
Run imsim.py on the instance catalog for the current visit and
for the desired sensor.
"""
from __future__ import absolute_import
import os
import sys
import re
import logging
import subprocess
sys.path.insert(0, os.environ['PYTHON_MODULES_DIR'])
import imsim_deep_utils

logging.basicConfig(format="run_imsim: %(message)s", level=logging.INFO,
                    stream=sys.stdout)
logger = logging.getLogger()

visit_info = imsim_deep_utils.get_visit_info()
sensor_number = int(os.environ['SENSOR_NUMBER'])
sensor_id = imsim_deep_utils.sensors()[sensor_number]
output_dir = os.path.join(os.environ['OUTPUT_DATA_DIR'],
                          '%07i' % visit_info.obsHistId)

try:
    instcat_file = \
        os.path.join(output_dir,
                     'instcat_' + re.sub('[:, ]', '_', sensor_id) + '.txt')
    imsim_deep_utils.trim_instcat(sensor_id, visit_info.instcat_file,
                                  instcat_file)
except ImportError:
    outfile = visit_info.instcat_file

command = ('imsim.py %s --outdir %s --sensor "%s" --log_level DEBUG'
           % (instcat_file, output_dir, sensor_id))
logger.info("running %s", command)
subprocess.check_call(command, shell=True)
