#!/usr/bin/env python
"""
Create instance catalogs via CatSim for each imsim_deep visit.
"""
from __future__ import absolute_import, print_function
import os
import copy
import sys
import logging
import warnings
import numpy as np
with warnings.catch_warnings():
    warnings.filterwarnings('ignore', 'Duplicate object type id', UserWarning)
    warnings.filterwarnings('ignore', 'duplicate object identifie', UserWarning)
    from lsst.sims.catalogs.db import CatalogDBObject
    from lsst.sims.catUtils.utils import ObservationMetaDataGenerator
    from lsst.sims.catUtils.exampleCatalogDefinitions \
        import DefaultPhoSimHeaderMap
    from lsst.sims.catUtils.exampleCatalogDefinitions.phoSimCatalogExamples \
        import PhoSimCatalogPoint, PhoSimCatalogSersic2D

import desc.imsim_deep_pipeline

logging.basicConfig(format="make_instcat: %(message)s", level=logging.INFO,
                    stream=sys.stdout)
logger = logging.getLogger()

db_config = dict(database='LSSTCATSIM',
                 port=1433,
                 host='fatboy.phys.washington.edu',
                 driver='mssql+pymssql')

opsim_db_file = os.environ['OPSIM_DB_FILE']
gen = ObservationMetaDataGenerator(database=opsim_db_file, driver='sqlite')

visit_info = desc.imsim_deep_pipeline.get_visit_info()
obs_md = gen.getObservationMetaData(obsHistID=visit_info.obsHistId,
                                    boundLength=visit_info.instcat_radius)[0]

# Apply dithering.  If any of the dithered summary table columns are missing,
# emit a warning, so that the user knows.
dithered_ra_name = 'randomDitherFieldPerVisitRA'
dithered_dec_name = 'randomDitherFieldPerVisitDec'
dithered_rot_tel_pos_name = 'ditheredRotTelPos'

# dither RA
try:
    obs_md.pointingRA = np.degrees(obs_md.OpsimMetaData[dithered_ra_name])
except KeyError:
    warnings.warn('ObservationMetaData does not contain %s data' % dithered_ra_name)

# dither Dec
try:
    obs_md.pointingDec = np.degrees(obs_md.OpsimMetaData[dithered_dec_name])
except KeyError:
    warnings.warn('ObservationMetaData does not contain %s data' % dithered_dec_name)

# dither rotTelPos and rotSkyPos
from lsst.sims.utils import _getRotSkyPos
phosim_header_map = copy.deepcopy(DefaultPhoSimHeaderMap)
try:
    dithered_rot_tel = obs_md.OpsimMetaData[dithered_rot_tel_pos_name]
    dithered_rot_sky = _getRotSkyPos(obs_md._pointingRA, obs_md._pointingDec,
                                     obs_md, dithered_rot_tel)

    obs_md.rotSkyPos = np.degrees(dithered_rot_sky)
    phosim_header_map['rottelpos'] = (dithered_rot_tel_pos_name, np.degrees)
except KeyError:
    warnings.warn('ObservationMetaData does not contain %s data' % dithered_rot_tel_pos_name)

star_objs = ['msstars', 'bhbstars', 'wdstars', 'rrlystars', 'cepheidstars']
gal_objs = ['galaxyBulge', 'galaxyDisk']

do_header = True
for objid in star_objs:
    logger.info("processing %s", objid)
    db_obj = CatalogDBObject.from_objid(objid, **db_config)
    phosim_object = PhoSimCatalogPoint(db_obj, obs_metadata=obs_md)
    if do_header:
        phosim_object.phoSimHeaderMap = phosim_header_map
        phosim_object.write_catalog(visit_info.instcat_file, write_mode='w',
                                    write_header=True, chunk_size=20000)
        do_header = False
    else:
        phosim_object.write_catalog(visit_info.instcat_file, write_mode='a',
                                    write_header=False, chunk_size=20000)

if os.environ['STARS_ONLY'] != 'true':
    for objid in gal_objs:
        logger.info("processing %s", objid)
        db_obj = CatalogDBObject.from_objid(objid, **db_config)
        phosim_object = PhoSimCatalogSersic2D(db_obj, obs_metadata=obs_md)
        phosim_object.write_catalog(visit_info.instcat_file, write_mode='a',
                                    write_header=False, chunk_size=20000)
